#include <stdio.h>
#include <string.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"

#include "i2s_manager.h"
#include "i2s_tx.pio.h"           // generated by pico_generate_pio_header
#include "../config/board_config.h"
#include "audio_constants.h"

// ======================================================
// HARDWARE RESOURCES
// ======================================================

static PIO  i2s_pio    = pio0;   // PIO block (pio0 is unclaimed by other subsystems)
static uint i2s_sm     = 0;      // state machine index, assigned at init
static uint pio_offset = 0;      // instruction memory offset

static int  dma_chan   = -1;     // DMA channel index, assigned at init

// ======================================================
// DOUBLE-BUFFER
//
// Two half-buffers of stereo 32-bit samples.
// DMA plays one half-buffer while core 1 fills the other.
//
// Buffer layout (per half):
//   tx_buf[idx][frame * 2 + 0] = left  channel word (24-bit audio << 8)
//   tx_buf[idx][frame * 2 + 1] = right channel word (same for mono)
//
// Aligned to 8 bytes for efficient 32-bit DMA burst reads.
// ======================================================

static uint32_t tx_buf[2][HALF_BUFFER_FRAMES * 2] __attribute__((aligned(8)));

static uint8_t play_idx = 0;   // half-buffer DMA is currently sending
static uint8_t fill_idx = 1;   // half-buffer core 1 should fill next

// ======================================================
// STATE
// ======================================================

static bool i2s_initialized = false;
static bool i2s_running      = false;

// ======================================================
// INTERNAL HELPERS
// ======================================================

static void dma_restart_on_buffer(uint8_t idx)
{
    // Set read address and trigger — DMA begins immediately.
    dma_channel_set_read_addr(dma_chan, tx_buf[idx], true /* trigger */);
}

// ======================================================
// PUBLIC API
// ======================================================

bool i2s_manager_init()
{
    if (i2s_initialized) return true;

    printf("I2S manager: initializing PIO + DMA...\n");

    // ---- Load PIO program ----
    i2s_sm     = pio_claim_unused_sm(i2s_pio, true);
    pio_offset = pio_add_program(i2s_pio, &i2s_tx_program);

    // i2s_tx_program_init() (defined in i2s_tx.pio % c-sdk {} block):
    //   - configures DATA, BCLK, LRCLK as PIO outputs
    //   - sets shift-left, 32-bit autopull, joined TX FIFO
    //   - computes and sets the clock divider for the target sample rate
    // The state machine is NOT enabled here — start_playback() does that.
    i2s_tx_program_init(
        i2s_pio, i2s_sm, pio_offset,
        PIN_AUDIO_I2S_DATA,    // OUT data pin (GPIO 28)
        PIN_AUDIO_I2S_BCLK     // side-set base: bit0=BCLK(26), bit1=LRCLK(27)
    );

    // ---- Claim DMA channel ----
    dma_chan = dma_claim_unused_channel(true);

    dma_channel_config cfg = dma_channel_get_default_config(dma_chan);
    channel_config_set_transfer_data_size(&cfg, DMA_SIZE_32);
    channel_config_set_dreq             (&cfg, pio_get_dreq(i2s_pio, i2s_sm, true));
    channel_config_set_read_increment   (&cfg, true);
    channel_config_set_write_increment  (&cfg, false);

    // Configure but don't trigger — start_playback() triggers the first transfer.
    dma_channel_configure(
        dma_chan, &cfg,
        &i2s_pio->txf[i2s_sm],   // destination: PIO TX FIFO
        tx_buf[play_idx],         // source: first half-buffer
        HALF_BUFFER_FRAMES * 2,   // word count: L+R per frame
        false                     // don't start yet
    );

    // Silence both buffers — DMA feeds zeros until audio rendering starts.
    memset(tx_buf, 0, sizeof(tx_buf));

    i2s_initialized = true;

    printf("I2S manager: PIO sm=%u offset=%u  DMA ch=%d\n",
           i2s_sm, pio_offset, dma_chan);
    printf("  BCLK  GPIO %d   LRCLK GPIO %d   DATA GPIO %d\n",
           PIN_AUDIO_I2S_BCLK, PIN_AUDIO_I2S_LRCLK, PIN_AUDIO_I2S_DATA);
    printf("  MIC   GPIO %d   (RX — Phase 2)\n", PIN_MIC_I2S_DATA);
    printf("  Half-buffer: %u frames  %u bytes  %.2f ms\n",
           HALF_BUFFER_FRAMES,
           (uint32_t)(HALF_BUFFER_FRAMES * 2 * 4),
           (double)HALF_BUFFER_FRAMES / AUDIO_SAMPLE_RATE_HZ * 1000.0);

    return true;
}

void i2s_manager_start_playback()
{
    if (!i2s_initialized) {
        printf("I2S manager: start_playback called before init — ignored.\n");
        return;
    }
    if (i2s_running) return;

    printf("I2S manager: starting PIO clock and DMA.\n");

    // Enable the PIO state machine.  BCLK and LRCLK begin toggling immediately.
    // The TLV320DAC3100 is an I2S slave and will lock to these clocks.
    pio_sm_set_enabled(i2s_pio, i2s_sm, true);

    // Kick off the first DMA transfer (silence buffer).
    dma_restart_on_buffer(play_idx);

    i2s_running = true;
}

bool i2s_manager_is_running()
{
    return i2s_running;
}

uint32_t* i2s_manager_get_next_write_buffer()
{
    if (!i2s_running) return nullptr;

    // Wait for the currently-playing DMA transfer to complete.
    // This blocks for approximately HALF_BUFFER_FRAMES / AUDIO_SAMPLE_RATE_HZ
    // ≈ 128 / 44100 ≈ 2.9 ms — the render budget for core 1 each iteration.
    dma_channel_wait_for_finish_blocking(dma_chan);

    // Swap buffers.  The buffer that core 1 just filled now becomes the play
    // buffer; the buffer DMA just finished is now free for core 1 to fill.
    play_idx ^= 1u;
    fill_idx ^= 1u;

    // Restart DMA immediately on the newly filled buffer.
    // Minimising this gap is important — a late restart causes a brief silence
    // glitch in the I2S stream.
    dma_restart_on_buffer(play_idx);

    return tx_buf[fill_idx];
}

void i2s_manager_write_silence()
{
    if (!i2s_running) return;
    memset(tx_buf[fill_idx], 0, HALF_BUFFER_FRAMES * 2 * sizeof(uint32_t));
}

// ---- Stub transitions (clock must never stop once started) ----

void i2s_manager_start_recording()
{
    // Phase 2: ICS-43432 RX capture.
    // For now just ensure the TX clock is running so BCLK reaches the mic.
    if (!i2s_running) i2s_manager_start_playback();
}

void i2s_manager_stop()
{
    // The TLV320DAC3100 requires continuous BCLK/WCLK — stopping the PIO
    // causes the DAC to lose sync and re-enter standby.  audio_core writes
    // silence to the buffer instead of calling this when idle.
    // This function is intentionally a no-op once the clock is running.
    if (!i2s_running) {
        printf("I2S manager: stop requested before clock started — no-op.\n");
    }
}
