#include <stdio.h>
#include <string.h>

#include "pico/stdlib.h"

#include "sample_loader.h"
#include "audio_constants.h"
#include "voice_config_parser.h"
#include "voice_definitions.h"
#include "../config/board_config.h"
#include "../config/firmware_config.h"
#include "../led/dotstar.h"

// Generated by CMake from assets/voice_config.txt.
// Contains the flash-embedded Tier 2 fallback voice configuration.
#include "voice_config_asset.h"

// ======================================================
// SD CARD DRIVER DEPENDENCY
//
// This file uses the FatFS API (f_mount, f_open, f_read, f_close, etc.).
// FatFS is the standard embedded FAT filesystem library by ChaN:
//   http://elm-chan.org/fsw/ff/
//
// FatFS SD SPI driver — carlk3/no-OS-FatFS-SD-SPI-RPi-Pico
// Added to the build via FetchContent in CMakeLists.txt.
// Hardware pin configuration is in board/hw_config.c.
#include "ff.h"       // FatFS core (f_open, f_read, f_close, etc.)
#include "sd_card.h"  // SPI SD card driver (sd_init_driver, etc.)
//
// Until the driver is added, all functions compile but return false/0.
// ======================================================

// ======================================================
// CARD DETECT
//
// PIN_SD_CARD_DETECT should be defined in board_config.h once the
// schematic is updated. The signal is active-LOW (card inserted = LOW)
// with a 10kΩ pull-up to 3.3V on the PCB.
//
// If PIN_SD_CARD_DETECT is not defined, card_is_present() falls back
// to an optimistic assumption (always true) so the driver still attempts
// an SPI probe — slow but functional without the hardware pin.
// ======================================================

static bool card_is_present()
{
#ifdef PIN_SD_CARD_DETECT
    // Active-low: LOW = card inserted, HIGH = absent.
    return gpio_get(PIN_SD_CARD_DETECT) == 0;
#else
    // No hardware detect pin — optimistically attempt access.
    // If the SD init fails, callers treat that as "no card".
    return true;
#endif
}


// ======================================================
// WAV FILE PARSER
//
// Supports 16-bit and 24-bit mono or stereo PCM .wav files.
// Only reads the RIFF/fmt/data chunks; ignores LIST, INFO, etc.
// Stereo files are read as mono by taking the left channel only.
//
// All WAV field values are little-endian (matches RP2040 native byte order).
// ======================================================

#pragma pack(push, 1)
struct WavRiffHeader {
    char     riff_id[4];    // "RIFF"
    uint32_t file_size;     // Total file size minus 8 bytes
    char     wave_id[4];    // "WAVE"
};

struct WavFmtChunk {
    char     chunk_id[4];   // "fmt "
    uint32_t chunk_size;    // Should be 16 for PCM
    uint16_t audio_format;  // 1 = PCM (uncompressed)
    uint16_t num_channels;  // 1 = mono, 2 = stereo
    uint32_t sample_rate;   // e.g. 44100
    uint32_t byte_rate;     // sample_rate * num_channels * bits_per_sample / 8
    uint16_t block_align;   // num_channels * bits_per_sample / 8
    uint16_t bits_per_sample; // 16 or 24
};

struct WavDataChunkHeader {
    char     chunk_id[4];   // "data"
    uint32_t chunk_size;    // Number of bytes of audio data
};
#pragma pack(pop)

// Parsed metadata returned by wav_read_header().
struct WavInfo {
    uint16_t num_channels;
    uint32_t sample_rate;
    uint16_t bits_per_sample;
    uint32_t data_offset;   // Byte offset of first audio sample in file
    uint32_t data_bytes;    // Total bytes of audio data
    uint32_t num_samples;   // Total sample frames (per channel)
};

// Read and validate the WAV header from an open FatFS file.
// Returns false if the file is not a valid PCM WAV.
// On success, populates 'info' and leaves the file position at the
// start of the audio data.
static bool wav_read_header(
    void*    /* FIL* */ file,
    WavInfo* info
) {
    // TODO: Replace void* with FIL* once FatFS is integrated.
    // The implementation below shows the intended logic; all f_read
    // calls need the FatFS-specific wrapper.
    //
    // UINT bytes_read = 0;
    //
    // WavRiffHeader riff;
    // if (f_read((FIL*)file, &riff, sizeof(riff), &bytes_read) != FR_OK ||
    //     bytes_read != sizeof(riff)) return false;
    // if (memcmp(riff.riff_id, "RIFF", 4) != 0) return false;
    // if (memcmp(riff.wave_id, "WAVE", 4) != 0) return false;
    //
    // WavFmtChunk fmt;
    // if (f_read((FIL*)file, &fmt, sizeof(fmt), &bytes_read) != FR_OK ||
    //     bytes_read != sizeof(fmt)) return false;
    // if (memcmp(fmt.chunk_id, "fmt ", 4) != 0) return false;
    // if (fmt.audio_format != 1) return false;  // PCM only
    // if (fmt.bits_per_sample != 16 && fmt.bits_per_sample != 24) return false;
    //
    // // Scan forward to find the "data" chunk (skip any non-data chunks).
    // WavDataChunkHeader data_hdr;
    // while (true) {
    //     if (f_read((FIL*)file, &data_hdr, sizeof(data_hdr), &bytes_read) != FR_OK ||
    //         bytes_read != sizeof(data_hdr)) return false;
    //     if (memcmp(data_hdr.chunk_id, "data", 4) == 0) break;
    //     f_lseek((FIL*)file, f_tell((FIL*)file) + data_hdr.chunk_size);
    // }
    //
    // info->num_channels    = fmt.num_channels;
    // info->sample_rate     = fmt.sample_rate;
    // info->bits_per_sample = fmt.bits_per_sample;
    // info->data_bytes      = data_hdr.chunk_size;
    // info->data_offset     = f_tell((FIL*)file);
    // info->num_samples     = data_hdr.chunk_size /
    //                         (fmt.num_channels * (fmt.bits_per_sample / 8));

    (void)file;
    (void)info;
    return false; // stub until FatFS is linked
}


// ======================================================
// SAMPLE STORAGE — SRAM POOL FOR SD-CARD-LOADED SAMPLES
//
// Samples loaded from the SD card are copied into this SRAM pool at
// startup so the core 1 render loop can access them without SD card
// latency. Each sample is stored as sign-extended 24-bit int32_t values.
//
// MEMORY BUDGET (RP2040 total SRAM = 264 KB):
//   Firmware + stack + DMA buffers: ~100 KB
//   Available for sample data:      ~128 KB
//   SAMPLE_POOL_INT32 = 32768 × 4 = 128 KB
//   At 44100 Hz mono: ~0.74 seconds total across ALL slots combined.
//
// This is intentionally small. It suits short percussive samples (drums,
// stabs). For longer samples use SD card streaming (future work).
//
// Flash-embedded assets do NOT use this pool — they live in flash and
// the synth engine accesses them directly via XIP pointers. Only their
// parsed int32_t header info is stored here.
// ======================================================

static constexpr uint32_t SAMPLE_POOL_INT32 = 32768; // 128 KB SRAM budget

static int32_t sample_pool[SAMPLE_POOL_INT32];
static uint32_t sample_pool_used = 0;

// Per-slot metadata: where in sample_pool the data starts and how long it is.
struct LoadedSample {
    bool     loaded;
    int32_t* data;         // Pointer into sample_pool
    uint32_t num_frames;   // Number of playable sample frames
    uint32_t sample_rate;  // Original sample rate (may differ from AUDIO_SAMPLE_RATE_HZ)
};

static LoadedSample loaded_samples[MAX_VOICES][MAX_SAMPLES_PER_VOICE];

static void loaded_samples_clear()
{
    memset(loaded_samples, 0, sizeof(loaded_samples));
    sample_pool_used = 0;
}


// ======================================================
// INTERNAL HELPERS
// ======================================================

// Allocate 'num_frames' int32_t slots from the pool.
// Returns nullptr if the pool is exhausted.
static int32_t* pool_alloc(uint32_t num_frames)
{
    if (sample_pool_used + num_frames > SAMPLE_POOL_INT32) {
        printf("SAMPLE_LOADER: pool exhausted (need %lu, have %lu)\n",
               (unsigned long)num_frames,
               (unsigned long)(SAMPLE_POOL_INT32 - sample_pool_used));
        return nullptr;
    }

    int32_t* ptr = &sample_pool[sample_pool_used];
    sample_pool_used += num_frames;
    return ptr;
}

// Load one WAV file from the SD card into the sample pool.
// Converts 16-bit samples to int32_t; sign-extends 24-bit samples.
// Stereo files are downmixed to mono (left channel only).
// Returns false if the file cannot be opened or is invalid.
static bool load_wav_file(
    const char*   path,
    int32_t**     out_data,
    uint32_t*     out_frames,
    uint32_t*     out_sample_rate
) {
    *out_data   = nullptr;
    *out_frames = 0;

    // --- SPI bus ownership ---
    // The SD card and DotStar LEDs share SPI0. Acquire the bus before
    // any SD card operation and release it immediately after.
    dotstar_spi_acquire();

    // TODO: Replace the stub below with actual FatFS calls:
    //
    // FIL file;
    // FRESULT res = f_open(&file, path, FA_READ);
    // if (res != FR_OK) {
    //     dotstar_spi_release();
    //     printf("SAMPLE_LOADER: cannot open %s (err %d)\n", path, res);
    //     return false;
    // }
    //
    // WavInfo info;
    // if (!wav_read_header(&file, &info)) {
    //     f_close(&file);
    //     dotstar_spi_release();
    //     printf("SAMPLE_LOADER: invalid WAV %s\n", path);
    //     return false;
    // }
    //
    // if (info.sample_rate != AUDIO_SAMPLE_RATE_HZ) {
    //     printf("SAMPLE_LOADER: WARNING %s sample rate %lu != %lu — pitch shift will occur\n",
    //            path, (unsigned long)info.sample_rate,
    //            (unsigned long)AUDIO_SAMPLE_RATE_HZ);
    // }
    //
    // uint32_t frames = info.num_samples;
    // if (frames > SAMPLE_MAX_FRAMES) {
    //     printf("SAMPLE_LOADER: %s truncated to %lu frames\n",
    //            path, (unsigned long)SAMPLE_MAX_FRAMES);
    //     frames = SAMPLE_MAX_FRAMES;
    // }
    //
    // int32_t* buf = pool_alloc(frames);
    // if (!buf) { f_close(&file); dotstar_spi_release(); return false; }
    //
    // uint32_t bytes_per_sample = info.bits_per_sample / 8;
    // uint32_t bytes_per_frame  = bytes_per_sample * info.num_channels;
    // uint8_t  raw[4];
    // UINT     br;
    //
    // for (uint32_t i = 0; i < frames; i++) {
    //     f_read(&file, raw, bytes_per_frame, &br);
    //     // Decode left channel only (mono or left of stereo)
    //     int32_t sample = 0;
    //     if (info.bits_per_sample == 16) {
    //         sample = (int32_t)(int16_t)((uint16_t)raw[0] | ((uint16_t)raw[1] << 8));
    //         sample <<= 8; // scale to 24-bit range
    //     } else { // 24-bit
    //         sample = (int32_t)raw[0] | ((int32_t)raw[1] << 8) | ((int32_t)raw[2] << 16);
    //         if (sample & 0x800000) sample |= 0xFF000000; // sign extend
    //     }
    //     buf[i] = sample;
    // }
    //
    // f_close(&file);
    // *out_data        = buf;
    // *out_frames      = frames;
    // *out_sample_rate = info.sample_rate;

    dotstar_spi_release();

    printf("SAMPLE_LOADER: load_wav_file('%s') — SD driver not yet linked\n", path);
    return false; // stub
}


// ======================================================
// PUBLIC API
// ======================================================

bool sample_loader_init(const char* voice_config_path)
{
    printf("SAMPLE_LOADER: init...\n");

    if (!card_is_present()) {
        printf("SAMPLE_LOADER: no SD card detected. Using built-in default voices.\n");
        return false;
    }

    // TODO: mount filesystem once here (not per-operation):
    // dotstar_spi_acquire();
    // FATFS fs;
    // FRESULT res = f_mount(&fs, "", 1);
    // dotstar_spi_release();
    // if (res != FR_OK) {
    //     printf("SAMPLE_LOADER: SD card mount failed (err %d).\n", res);
    //     return false;
    // }
    // printf("SAMPLE_LOADER: SD card mounted.\n");

    bool config_ok = sample_loader_load_voice_config(voice_config_path);

    if (config_ok) {
        uint32_t loaded = sample_loader_preload_samples();
        printf("SAMPLE_LOADER: init complete. %lu sample slots preloaded.\n",
               (unsigned long)loaded);
    } else {
        printf("SAMPLE_LOADER: no voice config found — using built-in defaults.\n");
    }

    return true;  // Partial success: even without config, card was detected.
}

const int32_t* sample_loader_get_sample(
    uint8_t   voice_index,
    uint8_t   note_index,
    uint32_t* out_num_frames,
    uint32_t* out_sample_rate
) {
    if (voice_index >= MAX_VOICES || note_index >= MAX_SAMPLES_PER_VOICE) {
        return nullptr;
    }

    const LoadedSample& slot = loaded_samples[voice_index][note_index];

    if (!slot.loaded || slot.data == nullptr || slot.num_frames == 0) {
        return nullptr;
    }

    if (out_num_frames)   *out_num_frames   = slot.num_frames;
    if (out_sample_rate)  *out_sample_rate  = slot.sample_rate;

    return slot.data;
}

bool sample_loader_load_voice_config(const char* path)
{
    if (!card_is_present()) {
        printf("SAMPLE_LOADER: no SD card detected, skipping config load.\n");
        return false;
    }

    printf("SAMPLE_LOADER: loading voice config from '%s'...\n", path);

    dotstar_spi_acquire();

    // TODO: Mount filesystem and iterate lines:
    //
    // FATFS fs;
    // if (f_mount(&fs, "", 1) != FR_OK) {
    //     dotstar_spi_release();
    //     printf("SAMPLE_LOADER: SD card mount failed.\n");
    //     return false;
    // }
    //
    // FIL file;
    // if (f_open(&file, path, FA_READ) != FR_OK) {
    //     dotstar_spi_release();
    //     printf("SAMPLE_LOADER: config file '%s' not found.\n", path);
    //     return false;
    // }
    //
    // voice_config_reset_stats();
    // char line[160];
    // uint32_t line_number = 0;
    // while (f_gets(line, sizeof(line), &file)) {
    //     line_number++;
    //     voice_config_parse_line(line, line_number);
    // }
    //
    // f_close(&file);

    dotstar_spi_release();

    // voice_config_print_stats();

    printf("SAMPLE_LOADER: load_voice_config — SD driver not yet linked\n");
    return false; // stub
}

uint32_t sample_loader_preload_samples()
{
    if (!card_is_present()) {
        printf("SAMPLE_LOADER: no SD card detected, skipping sample preload.\n");
        return 0;
    }

    printf("SAMPLE_LOADER: preloading samples...\n");

    loaded_samples_clear();

    uint32_t loaded_count = 0;

    for (uint8_t v = 0; v < MAX_VOICES; v++) {
        const VoiceDefinition* voice = voice_definitions_get(v);

        if (voice == nullptr || voice->type != VOICE_TYPE_PLAYBACK) {
            continue;
        }

        for (uint8_t s = 0; s < MAX_SAMPLES_PER_VOICE; s++) {
            const SampleSlot& slot = voice->samples[s];

            if (!slot.assigned || slot.filename[0] == '\0') {
                continue;
            }

            int32_t*  data   = nullptr;
            uint32_t  frames = 0;
            uint32_t  rate   = 0;

            if (load_wav_file(slot.filename, &data, &frames, &rate)) {
                loaded_samples[v][s].loaded      = true;
                loaded_samples[v][s].data        = data;
                loaded_samples[v][s].num_frames  = frames;
                loaded_samples[v][s].sample_rate = rate;

                printf("SAMPLE_LOADER: voice %u slot %u loaded %lu frames from %s\n",
                       v, s, (unsigned long)frames, slot.filename);
                loaded_count++;
            } else {
                printf("SAMPLE_LOADER: voice %u slot %u FAILED to load %s\n",
                       v, s, slot.filename);
            }
        }
    }

    printf("SAMPLE_LOADER: preload complete — %lu sample slots loaded.\n",
           (unsigned long)loaded_count);

    return loaded_count;
}

bool sample_loader_save_recording(
    const char*    path,
    const int32_t* samples,
    uint32_t       sample_count
) {
    if (samples == nullptr || sample_count == 0) {
        return false;
    }

    if (!card_is_present()) {
        printf("SAMPLE_LOADER: no SD card detected, cannot save recording.\n");
        return false;
    }

    printf("SAMPLE_LOADER: saving %lu samples to '%s'...\n",
           (unsigned long)sample_count, path);

    dotstar_spi_acquire();

    // TODO: Write a standard 24-bit mono PCM .wav file:
    //
    // FIL file;
    // if (f_open(&file, path, FA_WRITE | FA_CREATE_ALWAYS) != FR_OK) {
    //     dotstar_spi_release();
    //     printf("SAMPLE_LOADER: cannot create '%s'\n", path);
    //     return false;
    // }
    //
    // UINT bw;
    // uint32_t data_bytes = sample_count * 3; // 24-bit = 3 bytes per sample
    //
    // // RIFF header
    // WavRiffHeader riff = { {'R','I','F','F'}, (uint32_t)(36 + data_bytes), {'W','A','V','E'} };
    // f_write(&file, &riff, sizeof(riff), &bw);
    //
    // // fmt chunk (24-bit mono PCM)
    // WavFmtChunk fmt = {
    //     {'f','m','t',' '}, 16,
    //     1,                          // PCM
    //     1,                          // mono
    //     AUDIO_SAMPLE_RATE_HZ,
    //     AUDIO_SAMPLE_RATE_HZ * 3,  // byte_rate (mono 24-bit)
    //     3,                          // block_align (mono 24-bit)
    //     24                          // bits_per_sample
    // };
    // f_write(&file, &fmt, sizeof(fmt), &bw);
    //
    // // data chunk header
    // WavDataChunkHeader data_hdr = { {'d','a','t','a'}, data_bytes };
    // f_write(&file, &data_hdr, sizeof(data_hdr), &bw);
    //
    // // Write samples as 24-bit little-endian (3 bytes each)
    // for (uint32_t i = 0; i < sample_count; i++) {
    //     uint8_t bytes[3];
    //     int32_t s = samples[i];
    //     bytes[0] = (uint8_t)(s & 0xFF);
    //     bytes[1] = (uint8_t)((s >> 8) & 0xFF);
    //     bytes[2] = (uint8_t)((s >> 16) & 0xFF);
    //     f_write(&file, bytes, 3, &bw);
    // }
    //
    // f_close(&file);
    // printf("SAMPLE_LOADER: recording saved (%lu bytes).\n",
    //        (unsigned long)(36 + data_bytes));

    dotstar_spi_release();

    printf("SAMPLE_LOADER: save_recording — SD driver not yet linked\n");
    return false; // stub
}
